-- ============================================================
-- 01 — TABLA DE ACTIVIDADES (horario familiar anual: Día → Hora → Actividad)
-- Ejecutar PRIMERO en Supabase → SQL Editor → New query → Run.
-- Es seguro volver a ejecutarlo (no borra datos).
-- ============================================================

create table if not exists public.actividades (
  id               bigint generated by default as identity primary key,
  fecha            date        not null,                       -- día de la actividad
  hora             smallint    not null check (hora between 0 and 23),
                                                               -- hora de INICIO de la franja: 0 = 12 a. m.–1 a. m. … 23 = 11 p. m.–12 a. m.
  tiene_plazo      boolean     not null default false,         -- ¿Tiene plazo?
  fecha_plazo      date,                                       -- fecha límite (solo si tiene_plazo = true)
  que_hacer        text,                                       -- Qué toca hacer
  notas_generales  text,                                       -- Notas generales
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  -- Una actividad por franja: (fecha, hora) identifica cada celda sin ambigüedad.
  constraint actividades_fecha_hora_key unique (fecha, hora),

  -- tiene_plazo y fecha_plazo nunca pueden contradecirse.
  constraint actividades_plazo_coherente check (
    (tiene_plazo and fecha_plazo is not null)
    or (not tiene_plazo and fecha_plazo is null)
  )
);

-- updated_at se actualiza solo en cada UPDATE
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists actividades_set_updated_at on public.actividades;
create trigger actividades_set_updated_at
before update on public.actividades
for each row execute function public.set_updated_at();

-- Realtime: la app se actualiza sola cuando alguien cambia una actividad
do $$
begin
  alter publication supabase_realtime add table public.actividades;
exception
  when duplicate_object then null;  -- ya estaba agregada
end;
$$;

-- ============================================================
-- Seguridad a nivel de fila (RLS)
-- La app NO tiene login: usa la "anon/publishable key" desde el
-- navegador, así que la tabla necesita políticas que permitan leer
-- y escribir con esa clave. Sin ellas, todas las operaciones fallan.
-- (Consecuencia: cualquiera que tenga el enlace de la app puede ver
--  y editar el horario.)
-- ============================================================
alter table public.actividades enable row level security;

drop policy if exists "actividades lectura publica" on public.actividades;
create policy "actividades lectura publica"
  on public.actividades for select
  to anon, authenticated
  using (true);

drop policy if exists "actividades insercion publica" on public.actividades;
create policy "actividades insercion publica"
  on public.actividades for insert
  to anon, authenticated
  with check (true);

drop policy if exists "actividades actualizacion publica" on public.actividades;
create policy "actividades actualizacion publica"
  on public.actividades for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "actividades borrado publico" on public.actividades;
create policy "actividades borrado publico"
  on public.actividades for delete
  to anon, authenticated
  using (true);
